name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push API Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/api:latest -f ./API/Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/api:latest

      - name: Build and push Client Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/client:latest -f ./Client/Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/client:latest

